# DO NOT EDIT THIS FILE!
#
# Python module PacmanServer__POA generated by omniidl

import omniORB
omniORB.updateModule("PacmanServer__POA")

# ** 1. Stub files contributing to this module
import Pacman_idl

# ** 2. Sub-modules

# ** 3. End
